development:
  adapter: mysql2
  database: thesocialroute_development
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  password: ~
  pool: 5
  socket: /tmp/mysql.sock
  username: root
production:
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
test:
  adapter: mysql2
  database: thesocialroute_test
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  password: ~
  pool: 5
  socket: /tmp/mysql.sock
  username: root
